### ISSUE TITLE
No such file or directory: 'inter_single/eval.json'

### ISSUE THREAD

**Issue by gfrison** [allenai/bi-att-flow#16]
Hello,

I run the pre-trained weight with:
```
basic/run_single.sh ~/data/squad/dev-v1.1.json single.json
```

but I got:
```
File "/usr/lib/python3.5/gzip.py", line 163, in __init__
fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'inter_single/eval.json'
```

What did I make wrong? 

thank you

**Comment by webeng** [comment]
Can you try to use the full path to the data set and make sure you run the command from /path-to-bi-att-flow/bi-att-flow/?

Joan

**Comment by gfrison** [comment]
It was due to an error on libcudnn.so linking. solved.

**Comment by neufang** [comment]
What error on libcudnn.so linking? Could you give some details.

**Comment by webeng** [comment]
This is an issue with your CUDA installation. Check this out: https://github.com/jcjohnson/neural-style/issues/154 <https://github.com/jcjohnson/neural-style/issues/154>
Joan

**Comment by wnowak10** [comment]
If someone (@webeng @neufang @gfrison) could shed a bit more light on this, that'd be great. A bit unclear why  `FileNotFoundError: [Errno 2] No such file or directory: 'inter_single/eval.json'` connects to a CUDA install error. Thanks in advance!

**Comment by rjonesxmoz** [comment]
The file inter_single/eval.json does not appear to exist (the directory only contains data_single.json and shared_single.json). Is there any where to download that eval.json file?

**Comment by khliu1238** [comment]
look at error before this. There should be some error before it. In my case it was save/31/shared.json not found, which is because I extracted save.tar.gz under root dir (as instructed in the README), which  in fact should be extracted under it own save directory.

**Comment by diegotxegp** [comment]
[SOLVED]

3.1 Loading from pre-trained weights

Instead of training the model yourself, you can choose to use pre-trained weights that were used for SQuAD Leaderboard submission. Refer to this worksheet in CodaLab to reproduce the results. If you are unfamiliar with CodaLab, follow these simple steps (given that you met all prereqs above):

    1. Download save.zip from the worksheet and unzip it in the current directory.
    2. Copy glove.6B.100d.txt from your glove data folder ($HOME/data/glove/) to the current directory.
    3. To reproduce single model:

basic/run_single.sh $HOME/data/squad/dev-v1.1.json single.json

---------------------------------------------------------------------------------------------------------------
It is nothing related to CUDA.

At the moment you download the file "save.zip" (in fact, it is called "save.tar.gz") from the worksheet, you must decompress it at a folder called "save" within the BiDAF folder (BiDAF/save). However, the file "glove.6B.100d.txt" must be copied at the main folder where you have the BiDAF (BiDAF/glove.6B.100d.txt).

**Comment by hirenmayani** [comment]
I am not able to find save.zip or save.tar.gz on https://worksheets.codalab.org/worksheets/0x37a9b8c44f6845c28866267ef941c89d/ . did anyone changed it's name?

**Comment by diegotxegp** [comment]
Yes., you are right. Recently, I visited it back and saw that "save.tar.gz" didn't exist.
