### ISSUE TITLE
Extracting attention weights for a query

### ISSUE THREAD

**Issue by nikhilaravi** [allenai/bi-att-flow#26]
Where can I extract the attention weights for a query? I would like to visualise the attention for a query e.g. similar to this example:
<img width="589" alt="screen shot 2017-04-11 at 08 28 34" src="https://cloud.githubusercontent.com/assets/5912647/25046665/b90648ca-2100-11e7-8135-ae0d525960c4.png">

**Comment by seominjoon** [comment]
files in eval folder have this information. In particular, look for 'yp' (start index) and 'yp2' (end index). Note that these are not really the latent attention weights, though, but the predicted answer location.

**Comment by nikhilaravi** [comment]
@seominjoon thanks! 

 I've been trying to modify the `get_evaluations` function for the `ForwardEvaluator` [here](https://github.com/allenai/bi-att-flow/blob/demo/basic/evaluator.py#L369) , but at the moment there is only one value for `yp` and `yp2`. I tried modifying the function by adding the following code to use the  `get_span_score_pairs` function and then find the spans with the top 5 scores but they all seem to be from the same attention area.

```
        d = defaultdict(lambda: 0.0)
        for y1, y2 in zip(yp, yp2):
            for span, score in get_span_score_pairs(y1, y2):
                d[span] += score
        span = sorted(d.items(), key=lambda pair: pair[1], reverse=True)[:5]
        for s in span:
            print ('option', _get2(data_set.data['p'][0].strip(), data_set.data['x'][0], s[0]), 'score', s[1])

```
 This suggests to me that all the phrases are within the span given by `yp` and `yp2`. **How can I get more than one value for `yp` and `yp2`**?

Is this the correct way of approaching the problem? I would very much appreciate any help you can provide. Is there any way to access the latent weights?

Thanks very much!

**Comment by nikhilaravi** [comment]
@seominjoon would you be able to give me some advice on how I can solve my problem above?

**Comment by seominjoon** [comment]
@nikhilaravi Sorry about the delayed response! The shape of yp (and yp2) is [N, M, JX], where N is batch size, M is the number of sentences, and JX is the number of words in each sentence. Since for now the entire paragraph is considered as a single sentence, M = 1. So its shape will be [N, 1, JX]. Now, each value in this matrix indicates the probability that the answer starts at each location (and ends, for yp2). For instance, let say we have a sentence "Obama is born in Hawaii" (5 words). If yp = [0.1, 0.1, 0.1, 0.0, 0.7] (ignoring N and M dimensions for simplicity), then the answer is most likely to start at "Hawaii". If yp2 = [0.0, 0.2, 0.0, 0.2, 0.6], then the answer is most likely to end at "Hawaii" as well. Hence the final answer will be "Hawaii". So for visualization, you want to have two "attention" maps, one for yp and one for yp2.

**Comment by abaheti95** [comment]
@nikhilaravi @seominjoon 
Hi,
I want to get the latent attention scores on the question (which parts of the question does the model focus on ). Can you please point me to the segment of code that I should be looking at. I am not familiar with tensorflow and finding it very hard to understand.
